config/routes.rb
Rails.application.routes.draw do

  root 'home#index'
  resources :books
  resources :students
  resources :librarians
  resources :book_issues
  post 'search', to: "books#search"
  post 'searchbook', to: "students#searchbook"
  post 'searchuser', to: "books#searchuser"
  get 'mydashbord', to: "students#mydashbord"
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/ability.rb
# frozen_string_literal: true
class Ability
  include CanCan::Ability

  def initialize(user)
   if user.admin?
      can :manage, Book
      can :manage, BookIssue
   else
    cannot :manage, Book
    cannot :manage, BookIssue
   end
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
    belongs_to :user
    has_one :book_issues
end

app/models/book_issue.rb
class BookIssue < ApplicationRecord
    belongs_to :user
    belongs_to :book
end

app/models/user.rb
class User < ApplicationRecord

  has_many :books
  has_many :book_issues
  
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    protect_from_forgery with: :exception
    before_action :authenticate_user!
    before_action :update_allowed_parameters, if: :devise_controller?

    rescue_from CanCan::AccessDenied do | exception |
      redirect_to root_url, alert: exception.message
    end
  
  
    protected
  
    def update_allowed_parameters
      devise_parameter_sanitizer.permit(:sign_up) { |u| u.permit(:name, :surname, :email, :password)}
      devise_parameter_sanitizer.permit(:account_update) { |u| u.permit(:name, :surname, :email,:name,:surname,:admin,:password, :current_password)}
    end
end

app/controllers/book_issues_controller.rb
class BookIssuesController < ApplicationController
    load_and_authorize_resource

    def index
        @book_issues=BookIssue.all
    end

    def new
        @book_issue=BookIssue.new
    end

    def create
        @book_issue=BookIssue.new(book_issue_params)   
      
        if current_user.id == book_issue_params[:user_id].to_i
            render :new
        else
        @book=Book.find(book_issue_params[:book_id])
        if @book_issue.save!
            if @book.stoke>0 
                @book.stoke=@book.stoke-1
                @book.save
            else
             render :new
            end
        redirect_to book_issues_path
        else
        render :new
        end 
    end    
    end
    def destroy
        @bookissue=BookIssue.find(params[:id])
        @user=User.find_by(id:@bookissue.user_id)
        @book=Book.find_by(id:@bookissue.book_id)
        if Time.now.strftime("%Y-%m-%d")>@bookissue.return_date.to_s
            @user.totalfine=@user.totalfine+@book.late_fess
            @user.save
            if @bookissue.destroy
                @book.stoke=@book.stoke+1
                @book.save
             redirect_to librarians_path
            end
        else
            @user.totalfine=@user.totalfine+0
            @user.save
            if @bookissue.destroy
                @book.stoke=@book.stoke+1
                @book.save
                redirect_to librarians_path
            end
        end
    end
    private
  # Use callbacks to share common setup or constraints between actions.
  # Only allow a list of trusted parameters through.
  def book_issue_params
    params.require(:book_issue).permit(:book_id, :user_id, :issue_date,:return_date) 
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  
  load_and_authorize_resource 
  
  before_action :set_book, only: %i[ show edit update ]

  def index
    @books=Book.all
  end

  def new
    @book = Book.new
  end

  def show
  end
  
  def edit
  end
  
  def update
    if @book.update(book_params)
      redirect_to librarians_path
    else
    render :edit
    end
  end  
  def create
    @user=current_user
    @book=@user.books.new(book_params)
    if @book.save!
      redirect_to books_path
    else
      render :new
    end
  end 
  def search
    @books=Book.where("books.book_name LIKE :search",search: "%#{params[:query]}%")
  end
  def searchuser
    @user=User.find_by("users.name LIKE :search",search: "%#{params[:query]}%")
    if @user.nil?
     render 'librarians/index'  
    else
    @books=BookIssue.where(user_id: @user.id)
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_book
    @book = Book.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def book_params
    params.require(:book).permit(:book_name, :title, :author,:price,:stoke,:publish_date,:publication_name,:late_fess) 
  end

  
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
    def index
        if user_signed_in?
            if current_user.admin==true
             redirect_to librarians_path
            else
        
              redirect_to students_path
            end
        end
    end
end

app/controllers/librarians_controller.rb
class LibrariansController < ApplicationController
  load_and_authorize_resource :class =>"Book"
  before_action :set_book, only: %i[ show ]

  def index
    
  end

  def show
  end
  
  private
  # Use callbacks to share common setup or constraints between actions.
  def set_book
    @book = Book.find(params[:id])
  end
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
 
  def index
    @books=Book.all
  end

  def mydashbord
    @user=current_user
    @book_issues=@user.book_issues
  end
  def searchbook
    @books=Book.where("books.book_name LIKE :search",search: "%#{params[:query]}%")
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/book_issues_helper.rb
module BookIssuesHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/librarians_helper.rb
module LibrariansHelper
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/views/book_issues/_form.html.erb
<%= form_with(model: book_issue) do |form| %>

<br>
  <div class="field">
    <%= form.label :bookID %>
    <br>
    <%= form.number_field :book_id %>
  </div>
<br>
  <div class="field">
    <%= form.label :userid %>
    <br>
    <%= form.number_field :user_id %>
  </div>
<br>
   <div class="field">
    <%= form.label :issue_date %>
    <br>
    <%= form.date_field :issue_date %>
  </div>

<br>
  <div class="field">
    <%= form.label :return_date%>
    <br>
    <%= form.date_field :return_date%>
  </div>



<br>
  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/book_issues/index.html.erb
<br>
<h1>DashBord</h1>
      <th>USER ID </th>
      <th> BOOK ID</th>
      <th>ISSUE DATE</th>
      <th> RETURN DATE </th>
<br>
<%@book_issues.each do |bookissue|%>
<%=bookissue.user_id%>
<%=bookissue.book_id%>
<%=bookissue.issue_date%>
<%=bookissue.return_date%>
<br>
<%end%>
<%= link_to 'Back',  librarians_path %>

app/views/book_issues/new.html.erb
<h1>Issue BOOK</h1>

<%= render 'form', book_issue: @book_issue %>

<%= link_to 'Back',  librarians_path %>

app/views/books/_form.html.erb
<%= form_with(model: book) do |form| %>

<br>
  <div class="field">
    <%= form.label :book_name %>
    <br>
    <%= form.text_field :book_name %>
  </div>
<br>
  <div class="field">
    <%= form.label :title %>
    <br>
    <%= form.text_field :title %>
  </div>
<br>
   <div class="field">
    <%= form.label :author %>
    <br>
    <%= form.text_field :author %>
  </div>

<br>
  <div class="field">
    <%= form.label :price %>
    <br>
    <%= form.number_field :price%>
  </div>
  <br>
  <div class="field">
    <%= form.label :stoke %>
    <br>
    <%= form.number_field :stoke%>
  </div>
   <br>
  <div class="field">
    <%= form.label :Latefees %>
    <br>
    <%= form.number_field :late_fess%>
  </div>
<br>
     <div class="field">
    <%= form.label :publish_date %>
    <br>
    <%= form.date_field :publish_date %>
  </div>
  <br>
     <div class="field">
    <%= form.label :publication_name %>
    <br>
    <%= form.text_field :publication_name %>
  </div>

<br>
  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/books/create.html.erb
<h1>Books#create</h1>
<p>Find me in app/views/books/create.html.erb</p>

app/views/books/destroy.html.erb
<h1>Books#destroy</h1>
<p>Find me in app/views/books/destroy.html.erb</p>

app/views/books/edit.html.erb
<h1>Editing book</h1>

<%= render 'form', book: @book %>

<%= link_to 'Show', @book %> |
<%= link_to 'Back',  librarians_path %>

app/views/books/index.html.erb
<br>
<%@books.each do |book|%>
<%=book.book_name%>
<%=book.title%>
<%=book.stoke%>
<%=book.price%>
<%= link_to 'edit ', edit_book_path(book) %>
<br>
<%end%>
<%= link_to 'Back',  librarians_path %>

app/views/books/new.html.erb
<h1>ADD BOOK</h1>

<%= render 'form', book: @book %>

<%= link_to 'Back',  librarians_path %>

app/views/books/search.html.erb
<br>
<%@books.each do |book|%>
<%=book.book_name%>
<%=book.title%>
<%=book.stoke%>
<%=book.price%>
<%= link_to 'edit ', edit_book_path(book) %>
<br>
<%end%>
<%= link_to 'Back',  librarians_path %>

app/views/books/searchuser.html.erb
<br>
<%c=0%>
<h1>Name <%=@user.name%> your fine is due <%=@user.totalfine%></h1>
<%@books.each do |i|%>
<%=i.user_id%>
<%=i.book_id%>
<%=i.issue_date%>
<%=i.return_date%>
<%= link_to 'returnbook',book_issue_path(i),:method => :delete %>
<%c=c+1%>
<br>
<%end%>
<h1>total books Issued <%=c%></h1>
<%= link_to 'Back',  librarians_path %>

app/views/books/show.html.erb
<br>

<p>
  <strong>BookName:</strong>
  <%= @book.name %>
</p>

<p>
  <strong>Price:</strong>
  <%= @book.price %>
</p>

<p>
  <strong>Quantity:</strong>
  <%= @product.quantity %>
</p>

<%= link_to 'Edit', edit_product_path(@product) %> |
<%= link_to 'Back', products_path %>

app/views/books/update.html.erb
<h1>Books#update</h1>
<p>Find me in app/views/books/update.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>LibrarySystem</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <br>
    <% if notice %>
    <p class="alert alert-success"><%= notice %></p>
    <% end %>
    <% if alert %>
    <p class="alert alert-danger"><%= alert %></p>
    <% end %>
     <%if current_user%>
              <%= button_to 'Logut', '/users/sign_out', method: :delete %> 
             <%else%>
             <%= button_to 'Login', '/users/sign_in', method: :get %>
             <%= button_to 'Signup', '/users/sign_up', method: :get %>
             <%end%>
    <%= yield %>
  </body>
</html>

app/views/librarians/index.html.erb
<br>
<%= link_to 'add new book',  new_book_path %>
<br>
<%= link_to 'View books',  books_path %>
<br>
<%= link_to 'issue_book',  new_book_issue_path %>
<br>
<%= link_to 'Dashbord',  book_issues_path %>

<h1>Search BOOK</h1>
 <%= form_with url: "/search", method: :post do |form| %>
            <%= form.text_field :query,placeholder:"Search"%>
            <%= form.submit "search"%>
            <% end %>
<br>
<h1>Search USER BOOK</h1>
 <%= form_with url: "/searchuser", method: :post do |form| %>
            <%= form.text_field :query,placeholder:"Search"%>
            <%= form.submit "search"%>
            <% end %>

app/views/students/index.html.erb
<br>
<%= link_to 'MYBOOKS', mydashbord_path%>
<br>
<%= form_with url: "/searchbook", method: :post do |form| %>
            <%= form.text_field :query,placeholder:"Search"%>
            <%= form.submit "search"%>
            <% end %>

<h1>BOOKS AVAILABLE</h1>
<%@books.each do |book|%>
<%=book.book_name%>
<%=book.title%>
<%=book.stoke%>
<%=book.price%>
<br>
<%end%>
<%= link_to 'Back',  students_path %>

app/views/students/mydashbord.html.erb
<br>
<h1>Name <%=@user.name%> your fine is due <%=@user.totalfine%></h1>
  
      <th> BOOK ID</th>
      <th>ISSUE DATE</th>
      <th> RETURN DATE </th>
      <br>
<%@book_issues.each do |b|%>
<%=b.book_id%>
<%=b.issue_date%>
<%=b.return_date%>
<br>
<%end%>
<%= link_to 'Back',  students_path  %>

app/views/students/searchbook.html.erb
<br>
<%@books.each do |book|%>
<%=book.book_name%>
<%=book.title%>
<%=book.stoke%>
<%=book.price%>
<br>
<%end%>
<%= link_to 'Back',  students_path  %>